<?php
namespace common\widgets\FSearch;

use common\components\FHtml;
use common\widgets\BaseWidget;
use yii\helpers\ArrayHelper;

class FSearch extends BaseWidget
{
    public $search_type;

    protected function prepareData()
    {
        $this->display_type = !empty($this->display_type) ? $this->display_type : 'fsearch.php';
        parent::prepareData(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();
        $this->show_headline = false;
        return $this->render($this->display_type,
            [
                'search_type' => $this->search_type,
            ]);
    }


}

?>