SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `object_properties`;
CREATE TABLE `object_properties` (
    `id` bigint(20)  NOT NULL AUTO_INCREMENT ,
    `object_id` int(12)  NOT NULL  ,
    `object_type` varchar(100)  NOT NULL  ,
    `description` varchar(2000)  NULL  ,
    `content` text  NULL  ,
    `properties` text  NULL  ,
    `translations` text  NULL  ,
    `code` varchar(255)  NULL  ,
    `title` varchar(555)  NULL  ,
    `image` varchar(300)  NULL  ,
    `type` varchar(100)  NULL  ,
    `status` varchar(100)  NULL  ,
    `category_id` varchar(100)  NULL  ,
    `tags` varchar(2000)  NULL  ,
    `keywords` varchar(2000)  NULL  ,
    `view_count` int(11)  NULL  ,
    `download_count` int(11)  NULL  ,
    `purchase_count` int(11)  NULL  ,
    `like_count` int(11)  NULL  ,
    `comment_count` int(11)  NULL  ,
    `edit_count` int(11)  NULL  ,
    `favourite_count` int(11)  NULL  ,
    `created_date` timestamp  NULL  ,
    `created_user` int(11)  NULL  ,
    `modified_date` timestamp  NULL  ,
    `modified_user` int(11)  NULL  ,
    `application_id` varchar(100)  NULL  ,
    `history` text  NULL  ,
    `rate` decimal(10,2)  NULL  ,
    `rate_count` int(11)  NULL  ,
    `comments` text  NULL  ,
    `address` varchar(2000)  NULL  ,
    `address2` varchar(2000)  NULL  ,
    `mobile` varchar(255)  NULL  ,
    `phone` varchar(255)  NULL  ,
    `email1` varchar(255)  NULL  ,
    `email2` varchar(255)  NULL  ,
    `coordinate` varchar(255)  NULL  ,
    `is_top` tinyint(1)  NULL  ,
    `is_active` tinyint(1)  NULL  ,
    `is_hot` tinyint(1)  NULL  ,
    `is_new` tinyint(1)  NULL  ,
    `is_discount` tinyint(1)  NULL  ,
    `is_vip` tinyint(1)  NULL  ,
    `is_promotion` tinyint(1)  NULL  ,
    `is_expired` tinyint(1)  NULL  ,
    `is_completed` tinyint(1)  NULL  ,
    `author_name` varchar(255)  NULL  ,
    `author_id` int(11)  NULL  ,
    `user_id` int(11)  NULL  ,
    `product_id` int(11)  NULL  ,
    `provider_id` int(11)  NULL  ,
    `product_name` varchar(255)  NULL  ,
    `provider_name` varchar(255)  NULL  ,
    `publisher_id` int(11)  NULL  ,
    `publisher_name` varchar(255)  NULL  ,
    `banner` varchar(300)  NULL  ,
    `thumbnail` varchar(300)  NULL  ,
    `video` varchar(300)  NULL  ,
    `link_url` varchar(300)  NULL  ,
    `district` varchar(100)  NULL  ,
    `city` varchar(100)  NULL  ,
    `state` varchar(100)  NULL  ,
    `country` varchar(100)  NULL  ,
    `zip_code` varchar(255)  NULL  ,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


