<?php
namespace common\widgets\FContact;

use common\widgets\BaseWidget;

class FContact extends BaseWidget
{
    public $font_size = '';
    public $height = '';

    public function run()
    {
        $this->show_headline = false;
        self::prepareData();

        return $this->render($this->display_type,
            [
                'model' => $this->model,
                'title' => $this->title,
                'background_css' => $this->background_css,
                'color' => $this->color,
                'font_size' => $this->font_size,
                'url' => $this->link_url,
                'height' => $this->height,
                'margin' => $this->margin
            ]);
    }

    protected function prepareData()
    {
        if (empty($this->display_type))
            $this->display_type = 'contact';
        parent::prepareData(); // TODO: Change the autogenerated stub
    }
}

?>