<?php
/**
 * Created by PhpStorm.
 * User: Darkness
 * Date: 11/30/2016
 * Time: 2:00 PM
 */

namespace common\components;


use common\components\FConstant;
use common\config\FSettings;
use common\widgets\fview\FView;
use yii\base\Exception;
use Yii;
use yii\base\Theme;
use yii\helpers\VarDumper;
use yii\web\View;


class FTheme extends Theme
{
    public function init()
    {
        $this->pathMap = ['@frontend/views' => 'applications/' . FHtml::currentApplicationId()];

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getBasePath()
    {
        return parent::getBasePath();
    }


    public function getBaseUrl()
    {
        $application_folder = FHtml::currentApplicationId();
        $baseUrl = 'applications/' . $application_folder;
        return $baseUrl;
    }
}