<?php

namespace backend\modules\app\models;

use common\base\BaseActiveRecord;
use common\base\BaseAPIObject;
use common\components\FHtml;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "app_membership".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $service
 * @property string $type
 * @property integer $expiry
 * @property integer $is_active
 * @property string $created_date
 * @property string $modified_date
 * @property string $application_id
 */

class AppMembershipAPI extends BaseAPIObject
{
    public static function tableName()
    {
        //return 'app_membership';
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    const SERVICE_BUSINESS = 'business';
    const SERVICE_LIBRARY = 'library';
    const SERVICE_ECOMMERCE = 'ecommerce';
    const SERVICE_CONTENT = 'content';
    const TYPE_VIP = 'vip';
    const TYPE_PREMIUM = 'premium';
    const TYPE_PRO = 'pro';

    public function fields()
    {
        $fields = [
            'id',
            'user_id',
            'service',
            'type',
            'expiry',
            'is_active'
        ];

        return $fields;
    }
}