<?php

namespace backend\modules\app\models;

use backend\modules\app\App;
use backend\modules\smartscreen\models\SmartscreenStation;
use common\components\FHtml;
use yii\db\Exception;
use yii\helpers\Json;


class AppVersion extends AppVersionBase
{
    const LOOKUP = [
        'platform' => ['android', 'apps']
    ];

    const COLUMNS_UPLOAD = ['file'];

    public $order_by = 'is_default desc, package_version desc, modified_date desc';
    public $ime;
    public $is_upgrade;
    public $devices;

    const OBJECTS_META = [];

    public static function getLookupArray($column = '')
    {
        if (key_exists($column, self::LOOKUP))
            return self::LOOKUP[$column];
        return [];
    }

    public function fields()
    {
        $fields = array_merge(parent::fields(), self::OBJECTS_RELATED);

        foreach (self::COLUMNS_UPLOAD as $field) {
            $this->{$field} = FHtml::getFileURL($this->{$field}, $this->getTableName());
        }
        return $fields;
    }

    public function prepareCustomFields()
    {
        parent::prepareCustomFields();
    }

    public static function getRelatedObjects()
    {
        return self::OBJECTS_RELATED;
    }

    public static function getMetaObjects()
    {
        return self::OBJECTS_META;
    }

    public function beforeSave($insert)
    {
        if (empty($this->package_name))
            $this->package_name = "SMARTADS";

        if (empty($this->package_version))
            $this->package_version = FHtml::getNumeric(date("ymd"));

        if (empty($this->name))
            $this->name = $this->package_name . "-" . $this->package_version;

        if (empty($this->platform)) {
            $extension = substr($this->file, strpos($this->file, '.') + 1);

            if ($extension == 'zip') {
                $this->platform = 'apps';
            } elseif ($extension == 'apk') {
                $this->platform = 'android';
            } elseif (in_array($extension, ['jpg', 'png', 'gif', 'jpeg'])) {
                $this->platform = 'images';
            } elseif (in_array($extension, ['avi', 'mp4'])) {
                $this->platform = 'videos';
            } else {
                $this->platform = 'android';
            }
        }

        if (!isset($this->is_active))
            $this->is_active = true;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $attributes)
    {
        $this->is_upgrade = $this->loadFieldValue('_is_upgrade');
        $this->ime = $this->loadFieldValue('_ime');
        $this->devices = $this->loadFieldValue('_devices');
        $ime_array = (!empty($this->ime)) ? [$this->ime] : [];

        if ($this->is_upgrade) {
            if (is_array($this->devices) && !empty($this->devices)) {
                foreach ($this->devices as $device_id) {
                    $device_model = SmartscreenStation::findOne($device_id);
                    if (isset($device_model))
                        $ime_array[] = $device_model->ime;
                }
            }
            if (!empty($ime_array))
                $this->ime = implode(';', $ime_array);

            App::notifyAppVersionUpdate($this->ime, $this);
        }

        return parent::afterSave($insert, $attributes); // TODO: Change the autogenerated stub
    }

    public function beforeValidate()
    {
        if (empty($this->file))
            $this->file = '';
        return parent::beforeValidate();
    }

    public function getUniqueBooleanFields()
    {
        return ['is_default'];
    }

    public function getUniqueBooleanFieldsCondition()
    {
        return ['platform' => $this->platform, 'package_name' => $this->package_name];
    }
}
