<?php

namespace backend\modules\survey\models;

use common\components\FHtml;

class SurveyQuestionAPI extends SurveyQuestionBase
{
    //Customize fields to be displayed in API
    const COLUMNS_API = [
        'id',
        'name',
        'image',
        'content',
        'type',
        'allow_comment',
        'timeout',
        'hint',
        'answers'];

    public function fields()
    {
        $fields = $this::COLUMNS_API;

        return $fields;
    }

    public function rules()
    {
        //No Rules required for API object
        return [];
    }

    public function afterFind()
    {
        $this->answers = FHtml::decode($this->answers);
        if (!is_array($this->answers))
            $this->answers = [];
        if (empty($this->type))
            $this->type = empty($this->answers) ? 'text' : 'single';
        if (empty($this->answers))
            $this->type = 'text';
        if (empty($this->timeout))
            $this->timeout = 0;
        if (empty($this->answers))
            $this->answers = [];
        if (!empty($this->image))
            $this->image = FHtml::getFileUrl($this->image, self::tableName());

        $this->answers = \backend\modules\survey\Survey::prepareQuestionAnswers($this->answers);
        return parent::afterFind(); // TODO: Change the autogenerated stub
    }
}