<?php 
 return 
[
  'af' => 
  [
    'name' => 'Afghanistan',
    'capital' => 'Kabul',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'AFN',
    'currency_symbol' => '؋',
    'language' => 'ps',
    'language_name' => 'پښتو',
    'country_code' => '93',
    'timezone' => 'UTC+04:30',
  ],
  'ax' => 
  [
    'name' => 'Åland Islands',
    'capital' => 'Mariehamn',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'sv',
    'language_name' => 'svenska',
    'country_code' => '358',
    'timezone' => 'UTC+02:00',
  ],
  'al' => 
  [
    'name' => 'Albania',
    'capital' => 'Tirana',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'ALL',
    'currency_symbol' => 'L',
    'language' => 'sq',
    'language_name' => 'Shqip',
    'country_code' => '355',
    'timezone' => 'UTC+01:00',
  ],
  'dz' => 
  [
    'name' => 'Algeria',
    'capital' => 'Algiers',
    'region' => 'Africa',
    'subregion' => 'Northern Africa',
    'currency' => 'DZD',
    'currency_symbol' => 'د.ج',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '213',
    'timezone' => 'UTC+01:00',
  ],
  'as' => 
  [
    'name' => 'American Samoa',
    'capital' => 'Pago Pago',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1684',
    'timezone' => 'UTC-11:00',
  ],
  'ad' => 
  [
    'name' => 'Andorra',
    'capital' => 'Andorra la Vella',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'ca',
    'language_name' => 'català',
    'country_code' => '376',
    'timezone' => 'UTC+01:00',
  ],
  'ao' => 
  [
    'name' => 'Angola',
    'capital' => 'Luanda',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'AOA',
    'currency_symbol' => 'Kz',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '244',
    'timezone' => 'UTC+01:00',
  ],
  'ai' => 
  [
    'name' => 'Anguilla',
    'capital' => 'The Valley',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1264',
    'timezone' => 'UTC-04:00',
  ],
  'aq' => 
  [
    'name' => 'Antarctica',
    'capital' => '',
    'region' => 'Polar',
    'subregion' => '',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '672',
    'timezone' => 'UTC-03:00',
  ],
  'ag' => 
  [
    'name' => 'Antigua and Barbuda',
    'capital' => 'Saint John\'s',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1268',
    'timezone' => 'UTC-04:00',
  ],
  'ar' => 
  [
    'name' => 'Argentina',
    'capital' => 'Buenos Aires',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'ARS',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '54',
    'timezone' => 'UTC-03:00',
  ],
  'am' => 
  [
    'name' => 'Armenia',
    'capital' => 'Yerevan',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'AMD',
    'currency_symbol' => NULL,
    'language' => 'hy',
    'language_name' => 'Հայերեն',
    'country_code' => '374',
    'timezone' => 'UTC+04:00',
  ],
  'aw' => 
  [
    'name' => 'Aruba',
    'capital' => 'Oranjestad',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'AWG',
    'currency_symbol' => 'ƒ',
    'language' => 'nl',
    'language_name' => 'Nederlands',
    'country_code' => '297',
    'timezone' => 'UTC-04:00',
  ],
  'au' => 
  [
    'name' => 'Australia',
    'capital' => 'Canberra',
    'region' => 'Oceania',
    'subregion' => 'Australia and New Zealand',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '61',
    'timezone' => 'UTC+05:00',
  ],
  'at' => 
  [
    'name' => 'Austria',
    'capital' => 'Vienna',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'de',
    'language_name' => 'Deutsch',
    'country_code' => '43',
    'timezone' => 'UTC+01:00',
  ],
  'az' => 
  [
    'name' => 'Azerbaijan',
    'capital' => 'Baku',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'AZN',
    'currency_symbol' => NULL,
    'language' => 'az',
    'language_name' => 'azərbaycan dili',
    'country_code' => '994',
    'timezone' => 'UTC+04:00',
  ],
  'bs' => 
  [
    'name' => 'Bahamas',
    'capital' => 'Nassau',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'BSD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1242',
    'timezone' => 'UTC-05:00',
  ],
  'bh' => 
  [
    'name' => 'Bahrain',
    'capital' => 'Manama',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'BHD',
    'currency_symbol' => '.د.ب',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '973',
    'timezone' => 'UTC+03:00',
  ],
  'bd' => 
  [
    'name' => 'Bangladesh',
    'capital' => 'Dhaka',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'BDT',
    'currency_symbol' => '৳',
    'language' => 'bn',
    'language_name' => 'বাংলা',
    'country_code' => '880',
    'timezone' => 'UTC+06:00',
  ],
  'bb' => 
  [
    'name' => 'Barbados',
    'capital' => 'Bridgetown',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'BBD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1246',
    'timezone' => 'UTC-04:00',
  ],
  'by' => 
  [
    'name' => 'Belarus',
    'capital' => 'Minsk',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'BYN',
    'currency_symbol' => 'Br',
    'language' => 'be',
    'language_name' => 'беларуская мова',
    'country_code' => '375',
    'timezone' => 'UTC+03:00',
  ],
  'be' => 
  [
    'name' => 'Belgium',
    'capital' => 'Brussels',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'nl',
    'language_name' => 'Nederlands',
    'country_code' => '32',
    'timezone' => 'UTC+01:00',
  ],
  'bz' => 
  [
    'name' => 'Belize',
    'capital' => 'Belmopan',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'BZD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '501',
    'timezone' => 'UTC-06:00',
  ],
  'bj' => 
  [
    'name' => 'Benin',
    'capital' => 'Porto-Novo',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '229',
    'timezone' => 'UTC+01:00',
  ],
  'bm' => 
  [
    'name' => 'Bermuda',
    'capital' => 'Hamilton',
    'region' => 'Americas',
    'subregion' => 'Northern America',
    'currency' => 'BMD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1441',
    'timezone' => 'UTC-04:00',
  ],
  'bt' => 
  [
    'name' => 'Bhutan',
    'capital' => 'Thimphu',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'BTN',
    'currency_symbol' => 'Nu.',
    'language' => 'dz',
    'language_name' => 'རྫོང་ཁ',
    'country_code' => '975',
    'timezone' => 'UTC+06:00',
  ],
  'bo' => 
  [
    'name' => 'Bolivia (Plurinational State of]',
    'capital' => 'Sucre',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'BOB',
    'currency_symbol' => 'Bs.',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '591',
    'timezone' => 'UTC-04:00',
  ],
  'bq' => 
  [
    'name' => 'Bonaire, Sint Eustatius and Saba',
    'capital' => 'Kralendijk',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'nl',
    'language_name' => 'Nederlands',
    'country_code' => '5997',
    'timezone' => 'UTC-04:00',
  ],
  'ba' => 
  [
    'name' => 'Bosnia and Herzegovina',
    'capital' => 'Sarajevo',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'BAM',
    'currency_symbol' => NULL,
    'language' => 'bs',
    'language_name' => 'bosanski jezik',
    'country_code' => '387',
    'timezone' => 'UTC+01:00',
  ],
  'bw' => 
  [
    'name' => 'Botswana',
    'capital' => 'Gaborone',
    'region' => 'Africa',
    'subregion' => 'Southern Africa',
    'currency' => 'BWP',
    'currency_symbol' => 'P',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '267',
    'timezone' => 'UTC+02:00',
  ],
  'bv' => 
  [
    'name' => 'Bouvet Island',
    'capital' => '',
    'region' => '',
    'subregion' => '',
    'currency' => 'NOK',
    'currency_symbol' => 'kr',
    'language' => 'no',
    'language_name' => 'Norsk',
    'country_code' => '',
    'timezone' => 'UTC+01:00',
  ],
  'br' => 
  [
    'name' => 'Brazil',
    'capital' => 'Brasília',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'BRL',
    'currency_symbol' => 'R$',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '55',
    'timezone' => 'UTC-05:00',
  ],
  'io' => 
  [
    'name' => 'British Indian Ocean Territory',
    'capital' => 'Diego Garcia',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '246',
    'timezone' => 'UTC+06:00',
  ],
  'um' => 
  [
    'name' => 'United States Minor Outlying Islands',
    'capital' => '',
    'region' => 'Americas',
    'subregion' => 'Northern America',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '',
    'timezone' => 'UTC-11:00',
  ],
  'vg' => 
  [
    'name' => 'Virgin Islands (British]',
    'capital' => 'Road Town',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => NULL,
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1284',
    'timezone' => 'UTC-04:00',
  ],
  'vi' => 
  [
    'name' => 'Virgin Islands (U.S.]',
    'capital' => 'Charlotte Amalie',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1 340',
    'timezone' => 'UTC-04:00',
  ],
  'bn' => 
  [
    'name' => 'Brunei Darussalam',
    'capital' => 'Bandar Seri Begawan',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'BND',
    'currency_symbol' => '$',
    'language' => 'ms',
    'language_name' => 'bahasa Melayu',
    'country_code' => '673',
    'timezone' => 'UTC+08:00',
  ],
  'bg' => 
  [
    'name' => 'Bulgaria',
    'capital' => 'Sofia',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'BGN',
    'currency_symbol' => 'лв',
    'language' => 'bg',
    'language_name' => 'български език',
    'country_code' => '359',
    'timezone' => 'UTC+02:00',
  ],
  'bf' => 
  [
    'name' => 'Burkina Faso',
    'capital' => 'Ouagadougou',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '226',
    'timezone' => 'UTC',
  ],
  'bi' => 
  [
    'name' => 'Burundi',
    'capital' => 'Bujumbura',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'BIF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '257',
    'timezone' => 'UTC+02:00',
  ],
  'kh' => 
  [
    'name' => 'Cambodia',
    'capital' => 'Phnom Penh',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'KHR',
    'currency_symbol' => '៛',
    'language' => 'km',
    'language_name' => 'ខ្មែរ',
    'country_code' => '855',
    'timezone' => 'UTC+07:00',
  ],
  'cm' => 
  [
    'name' => 'Cameroon',
    'capital' => 'Yaoundé',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'XAF',
    'currency_symbol' => 'Fr',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '237',
    'timezone' => 'UTC+01:00',
  ],
  'ca' => 
  [
    'name' => 'Canada',
    'capital' => 'Ottawa',
    'region' => 'Americas',
    'subregion' => 'Northern America',
    'currency' => 'CAD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1',
    'timezone' => 'UTC-08:00',
  ],
  'cv' => 
  [
    'name' => 'Cabo Verde',
    'capital' => 'Praia',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'CVE',
    'currency_symbol' => 'Esc',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '238',
    'timezone' => 'UTC-01:00',
  ],
  'ky' => 
  [
    'name' => 'Cayman Islands',
    'capital' => 'George Town',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'KYD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1345',
    'timezone' => 'UTC-05:00',
  ],
  'cf' => 
  [
    'name' => 'Central African Republic',
    'capital' => 'Bangui',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'XAF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '236',
    'timezone' => 'UTC+01:00',
  ],
  'td' => 
  [
    'name' => 'Chad',
    'capital' => 'N\'Djamena',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'XAF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '235',
    'timezone' => 'UTC+01:00',
  ],
  'cl' => 
  [
    'name' => 'Chile',
    'capital' => 'Santiago',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'CLP',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '56',
    'timezone' => 'UTC-06:00',
  ],
  'cn' => 
  [
    'name' => 'China',
    'capital' => 'Beijing',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'CNY',
    'currency_symbol' => '¥',
    'language' => 'zh',
    'language_name' => '中文 (Zhōngwén]',
    'country_code' => '86',
    'timezone' => 'UTC+08:00',
  ],
  'cx' => 
  [
    'name' => 'Christmas Island',
    'capital' => 'Flying Fish Cove',
    'region' => 'Oceania',
    'subregion' => 'Australia and New Zealand',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '61',
    'timezone' => 'UTC+07:00',
  ],
  'cc' => 
  [
    'name' => 'Cocos (Keeling] Islands',
    'capital' => 'West Island',
    'region' => 'Oceania',
    'subregion' => 'Australia and New Zealand',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '61',
    'timezone' => 'UTC+06:30',
  ],
  'co' => 
  [
    'name' => 'Colombia',
    'capital' => 'Bogotá',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'COP',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '57',
    'timezone' => 'UTC-05:00',
  ],
  'km' => 
  [
    'name' => 'Comoros',
    'capital' => 'Moroni',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'KMF',
    'currency_symbol' => 'Fr',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '269',
    'timezone' => 'UTC+03:00',
  ],
  'cg' => 
  [
    'name' => 'Congo',
    'capital' => 'Brazzaville',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'XAF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '242',
    'timezone' => 'UTC+01:00',
  ],
  'cd' => 
  [
    'name' => 'Congo (Democratic Republic of the]',
    'capital' => 'Kinshasa',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'CDF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '243',
    'timezone' => 'UTC+01:00',
  ],
  'ck' => 
  [
    'name' => 'Cook Islands',
    'capital' => 'Avarua',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'NZD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '682',
    'timezone' => 'UTC-10:00',
  ],
  'cr' => 
  [
    'name' => 'Costa Rica',
    'capital' => 'San José',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'CRC',
    'currency_symbol' => '₡',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '506',
    'timezone' => 'UTC-06:00',
  ],
  'hr' => 
  [
    'name' => 'Croatia',
    'capital' => 'Zagreb',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'HRK',
    'currency_symbol' => 'kn',
    'language' => 'hr',
    'language_name' => 'hrvatski jezik',
    'country_code' => '385',
    'timezone' => 'UTC+01:00',
  ],
  'cu' => 
  [
    'name' => 'Cuba',
    'capital' => 'Havana',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'CUC',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '53',
    'timezone' => 'UTC-05:00',
  ],
  'cw' => 
  [
    'name' => 'Curaçao',
    'capital' => 'Willemstad',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'ANG',
    'currency_symbol' => 'ƒ',
    'language' => 'nl',
    'language_name' => 'Nederlands',
    'country_code' => '599',
    'timezone' => 'UTC-04:00',
  ],
  'cy' => 
  [
    'name' => 'Cyprus',
    'capital' => 'Nicosia',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'el',
    'language_name' => 'ελληνικά',
    'country_code' => '357',
    'timezone' => 'UTC+02:00',
  ],
  'cz' => 
  [
    'name' => 'Czech Republic',
    'capital' => 'Prague',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'CZK',
    'currency_symbol' => 'Kč',
    'language' => 'cs',
    'language_name' => 'čeština',
    'country_code' => '420',
    'timezone' => 'UTC+01:00',
  ],
  'dk' => 
  [
    'name' => 'Denmark',
    'capital' => 'Copenhagen',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'DKK',
    'currency_symbol' => 'kr',
    'language' => 'da',
    'language_name' => 'dansk',
    'country_code' => '45',
    'timezone' => 'UTC-04:00',
  ],
  'dj' => 
  [
    'name' => 'Djibouti',
    'capital' => 'Djibouti',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'DJF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '253',
    'timezone' => 'UTC+03:00',
  ],
  'dm' => 
  [
    'name' => 'Dominica',
    'capital' => 'Roseau',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1767',
    'timezone' => 'UTC-04:00',
  ],
  'do' => 
  [
    'name' => 'Dominican Republic',
    'capital' => 'Santo Domingo',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'DOP',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '1809',
    'timezone' => 'UTC-04:00',
  ],
  'ec' => 
  [
    'name' => 'Ecuador',
    'capital' => 'Quito',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '593',
    'timezone' => 'UTC-06:00',
  ],
  'eg' => 
  [
    'name' => 'Egypt',
    'capital' => 'Cairo',
    'region' => 'Africa',
    'subregion' => 'Northern Africa',
    'currency' => 'EGP',
    'currency_symbol' => '£',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '20',
    'timezone' => 'UTC+02:00',
  ],
  'sv' => 
  [
    'name' => 'El Salvador',
    'capital' => 'San Salvador',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '503',
    'timezone' => 'UTC-06:00',
  ],
  'gq' => 
  [
    'name' => 'Equatorial Guinea',
    'capital' => 'Malabo',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'XAF',
    'currency_symbol' => 'Fr',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '240',
    'timezone' => 'UTC+01:00',
  ],
  'er' => 
  [
    'name' => 'Eritrea',
    'capital' => 'Asmara',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'ERN',
    'currency_symbol' => 'Nfk',
    'language' => 'ti',
    'language_name' => 'ትግርኛ',
    'country_code' => '291',
    'timezone' => 'UTC+03:00',
  ],
  'ee' => 
  [
    'name' => 'Estonia',
    'capital' => 'Tallinn',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'et',
    'language_name' => 'eesti',
    'country_code' => '372',
    'timezone' => 'UTC+02:00',
  ],
  'et' => 
  [
    'name' => 'Ethiopia',
    'capital' => 'Addis Ababa',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'ETB',
    'currency_symbol' => 'Br',
    'language' => 'am',
    'language_name' => 'አማርኛ',
    'country_code' => '251',
    'timezone' => 'UTC+03:00',
  ],
  'fk' => 
  [
    'name' => 'Falkland Islands (Malvinas]',
    'capital' => 'Stanley',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'FKP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '500',
    'timezone' => 'UTC-04:00',
  ],
  'fo' => 
  [
    'name' => 'Faroe Islands',
    'capital' => 'Tórshavn',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'DKK',
    'currency_symbol' => 'kr',
    'language' => 'fo',
    'language_name' => 'føroyskt',
    'country_code' => '298',
    'timezone' => 'UTC+00:00',
  ],
  'fj' => 
  [
    'name' => 'Fiji',
    'capital' => 'Suva',
    'region' => 'Oceania',
    'subregion' => 'Melanesia',
    'currency' => 'FJD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '679',
    'timezone' => 'UTC+12:00',
  ],
  'fi' => 
  [
    'name' => 'Finland',
    'capital' => 'Helsinki',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fi',
    'language_name' => 'suomi',
    'country_code' => '358',
    'timezone' => 'UTC+02:00',
  ],
  'fr' => 
  [
    'name' => 'France',
    'capital' => 'Paris',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '33',
    'timezone' => 'UTC-10:00',
  ],
  'gf' => 
  [
    'name' => 'French Guiana',
    'capital' => 'Cayenne',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '594',
    'timezone' => 'UTC-03:00',
  ],
  'pf' => 
  [
    'name' => 'French Polynesia',
    'capital' => 'Papeetē',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'XPF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '689',
    'timezone' => 'UTC-10:00',
  ],
  'tf' => 
  [
    'name' => 'French Southern Territories',
    'capital' => 'Port-aux-Français',
    'region' => 'Africa',
    'subregion' => 'Southern Africa',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '',
    'timezone' => 'UTC+05:00',
  ],
  'ga' => 
  [
    'name' => 'Gabon',
    'capital' => 'Libreville',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'XAF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '241',
    'timezone' => 'UTC+01:00',
  ],
  'gm' => 
  [
    'name' => 'Gambia',
    'capital' => 'Banjul',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'GMD',
    'currency_symbol' => 'D',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '220',
    'timezone' => 'UTC+00:00',
  ],
  'ge' => 
  [
    'name' => 'Georgia',
    'capital' => 'Tbilisi',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'GEL',
    'currency_symbol' => 'ლ',
    'language' => 'ka',
    'language_name' => 'ქართული',
    'country_code' => '995',
    'timezone' => 'UTC-05:00',
  ],
  'de' => 
  [
    'name' => 'Germany',
    'capital' => 'Berlin',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'de',
    'language_name' => 'Deutsch',
    'country_code' => '49',
    'timezone' => 'UTC+01:00',
  ],
  'gh' => 
  [
    'name' => 'Ghana',
    'capital' => 'Accra',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'GHS',
    'currency_symbol' => '₵',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '233',
    'timezone' => 'UTC',
  ],
  'gi' => 
  [
    'name' => 'Gibraltar',
    'capital' => 'Gibraltar',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'GIP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '350',
    'timezone' => 'UTC+01:00',
  ],
  'gr' => 
  [
    'name' => 'Greece',
    'capital' => 'Athens',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'el',
    'language_name' => 'ελληνικά',
    'country_code' => '30',
    'timezone' => 'UTC+02:00',
  ],
  'gl' => 
  [
    'name' => 'Greenland',
    'capital' => 'Nuuk',
    'region' => 'Americas',
    'subregion' => 'Northern America',
    'currency' => 'DKK',
    'currency_symbol' => 'kr',
    'language' => 'kl',
    'language_name' => 'kalaallisut',
    'country_code' => '299',
    'timezone' => 'UTC-04:00',
  ],
  'gd' => 
  [
    'name' => 'Grenada',
    'capital' => 'St. George\'s',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1473',
    'timezone' => 'UTC-04:00',
  ],
  'gp' => 
  [
    'name' => 'Guadeloupe',
    'capital' => 'Basse-Terre',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '590',
    'timezone' => 'UTC-04:00',
  ],
  'gu' => 
  [
    'name' => 'Guam',
    'capital' => 'Hagåtña',
    'region' => 'Oceania',
    'subregion' => 'Micronesia',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1671',
    'timezone' => 'UTC+10:00',
  ],
  'gt' => 
  [
    'name' => 'Guatemala',
    'capital' => 'Guatemala City',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'GTQ',
    'currency_symbol' => 'Q',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '502',
    'timezone' => 'UTC-06:00',
  ],
  'gg' => 
  [
    'name' => 'Guernsey',
    'capital' => 'St. Peter Port',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'GBP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '44',
    'timezone' => 'UTC+00:00',
  ],
  'gn' => 
  [
    'name' => 'Guinea',
    'capital' => 'Conakry',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'GNF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '224',
    'timezone' => 'UTC',
  ],
  'gw' => 
  [
    'name' => 'Guinea-Bissau',
    'capital' => 'Bissau',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '245',
    'timezone' => 'UTC',
  ],
  'gy' => 
  [
    'name' => 'Guyana',
    'capital' => 'Georgetown',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'GYD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '592',
    'timezone' => 'UTC-04:00',
  ],
  'ht' => 
  [
    'name' => 'Haiti',
    'capital' => 'Port-au-Prince',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'HTG',
    'currency_symbol' => 'G',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '509',
    'timezone' => 'UTC-05:00',
  ],
  'hm' => 
  [
    'name' => 'Heard Island and McDonald Islands',
    'capital' => '',
    'region' => '',
    'subregion' => '',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '',
    'timezone' => 'UTC+05:00',
  ],
  'va' => 
  [
    'name' => 'Holy See',
    'capital' => 'Rome',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'la',
    'language_name' => 'latine',
    'country_code' => '379',
    'timezone' => 'UTC+01:00',
  ],
  'hn' => 
  [
    'name' => 'Honduras',
    'capital' => 'Tegucigalpa',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'HNL',
    'currency_symbol' => 'L',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '504',
    'timezone' => 'UTC-06:00',
  ],
  'hk' => 
  [
    'name' => 'Hong Kong',
    'capital' => 'City of Victoria',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'HKD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '852',
    'timezone' => 'UTC+08:00',
  ],
  'hu' => 
  [
    'name' => 'Hungary',
    'capital' => 'Budapest',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'HUF',
    'currency_symbol' => 'Ft',
    'language' => 'hu',
    'language_name' => 'magyar',
    'country_code' => '36',
    'timezone' => 'UTC+01:00',
  ],
  'is' => 
  [
    'name' => 'Iceland',
    'capital' => 'Reykjavík',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'ISK',
    'currency_symbol' => 'kr',
    'language' => 'is',
    'language_name' => 'Íslenska',
    'country_code' => '354',
    'timezone' => 'UTC',
  ],
  'in' => 
  [
    'name' => 'India',
    'capital' => 'New Delhi',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'INR',
    'currency_symbol' => '₹',
    'language' => 'hi',
    'language_name' => 'हिन्दी',
    'country_code' => '91',
    'timezone' => 'UTC+05:30',
  ],
  'id' => 
  [
    'name' => 'Indonesia',
    'capital' => 'Jakarta',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'IDR',
    'currency_symbol' => 'Rp',
    'language' => 'id',
    'language_name' => 'Bahasa Indonesia',
    'country_code' => '62',
    'timezone' => 'UTC+07:00',
  ],
  'ci' => 
  [
    'name' => 'Côte d\'Ivoire',
    'capital' => 'Yamoussoukro',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '225',
    'timezone' => 'UTC',
  ],
  'ir' => 
  [
    'name' => 'Iran (Islamic Republic of]',
    'capital' => 'Tehran',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'IRR',
    'currency_symbol' => '﷼',
    'language' => 'fa',
    'language_name' => 'فارسی',
    'country_code' => '98',
    'timezone' => 'UTC+03:30',
  ],
  'iq' => 
  [
    'name' => 'Iraq',
    'capital' => 'Baghdad',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'IQD',
    'currency_symbol' => 'ع.د',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '964',
    'timezone' => 'UTC+03:00',
  ],
  'ie' => 
  [
    'name' => 'Ireland',
    'capital' => 'Dublin',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'ga',
    'language_name' => 'Gaeilge',
    'country_code' => '353',
    'timezone' => 'UTC',
  ],
  'im' => 
  [
    'name' => 'Isle of Man',
    'capital' => 'Douglas',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'GBP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '44',
    'timezone' => 'UTC+00:00',
  ],
  'il' => 
  [
    'name' => 'Israel',
    'capital' => 'Jerusalem',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'ILS',
    'currency_symbol' => '₪',
    'language' => 'he',
    'language_name' => 'עברית',
    'country_code' => '972',
    'timezone' => 'UTC+02:00',
  ],
  'it' => 
  [
    'name' => 'Italy',
    'capital' => 'Rome',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'it',
    'language_name' => 'Italiano',
    'country_code' => '39',
    'timezone' => 'UTC+01:00',
  ],
  'jm' => 
  [
    'name' => 'Jamaica',
    'capital' => 'Kingston',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'JMD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1876',
    'timezone' => 'UTC-05:00',
  ],
  'jp' => 
  [
    'name' => 'Japan',
    'capital' => 'Tokyo',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'JPY',
    'currency_symbol' => '¥',
    'language' => 'ja',
    'language_name' => '日本語 (にほんご]',
    'country_code' => '81',
    'timezone' => 'UTC+09:00',
  ],
  'je' => 
  [
    'name' => 'Jersey',
    'capital' => 'Saint Helier',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'GBP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '44',
    'timezone' => 'UTC+01:00',
  ],
  'jo' => 
  [
    'name' => 'Jordan',
    'capital' => 'Amman',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'JOD',
    'currency_symbol' => 'د.ا',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '962',
    'timezone' => 'UTC+03:00',
  ],
  'kz' => 
  [
    'name' => 'Kazakhstan',
    'capital' => 'Astana',
    'region' => 'Asia',
    'subregion' => 'Central Asia',
    'currency' => 'KZT',
    'currency_symbol' => NULL,
    'language' => 'kk',
    'language_name' => 'қазақ тілі',
    'country_code' => '76',
    'timezone' => 'UTC+05:00',
  ],
  'ke' => 
  [
    'name' => 'Kenya',
    'capital' => 'Nairobi',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'KES',
    'currency_symbol' => 'Sh',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '254',
    'timezone' => 'UTC+03:00',
  ],
  'ki' => 
  [
    'name' => 'Kiribati',
    'capital' => 'South Tarawa',
    'region' => 'Oceania',
    'subregion' => 'Micronesia',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '686',
    'timezone' => 'UTC+12:00',
  ],
  'kw' => 
  [
    'name' => 'Kuwait',
    'capital' => 'Kuwait City',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'KWD',
    'currency_symbol' => 'د.ك',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '965',
    'timezone' => 'UTC+03:00',
  ],
  'kg' => 
  [
    'name' => 'Kyrgyzstan',
    'capital' => 'Bishkek',
    'region' => 'Asia',
    'subregion' => 'Central Asia',
    'currency' => 'KGS',
    'currency_symbol' => 'с',
    'language' => 'ky',
    'language_name' => 'Кыргызча',
    'country_code' => '996',
    'timezone' => 'UTC+06:00',
  ],
  'la' => 
  [
    'name' => 'Lao People\'s Democratic Republic',
    'capital' => 'Vientiane',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'LAK',
    'currency_symbol' => '₭',
    'language' => 'lo',
    'language_name' => 'ພາສາລາວ',
    'country_code' => '856',
    'timezone' => 'UTC+07:00',
  ],
  'lv' => 
  [
    'name' => 'Latvia',
    'capital' => 'Riga',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'lv',
    'language_name' => 'latviešu valoda',
    'country_code' => '371',
    'timezone' => 'UTC+02:00',
  ],
  'lb' => 
  [
    'name' => 'Lebanon',
    'capital' => 'Beirut',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'LBP',
    'currency_symbol' => 'ل.ل',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '961',
    'timezone' => 'UTC+02:00',
  ],
  'ls' => 
  [
    'name' => 'Lesotho',
    'capital' => 'Maseru',
    'region' => 'Africa',
    'subregion' => 'Southern Africa',
    'currency' => 'LSL',
    'currency_symbol' => 'L',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '266',
    'timezone' => 'UTC+02:00',
  ],
  'lr' => 
  [
    'name' => 'Liberia',
    'capital' => 'Monrovia',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'LRD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '231',
    'timezone' => 'UTC',
  ],
  'ly' => 
  [
    'name' => 'Libya',
    'capital' => 'Tripoli',
    'region' => 'Africa',
    'subregion' => 'Northern Africa',
    'currency' => 'LYD',
    'currency_symbol' => 'ل.د',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '218',
    'timezone' => 'UTC+01:00',
  ],
  'li' => 
  [
    'name' => 'Liechtenstein',
    'capital' => 'Vaduz',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'CHF',
    'currency_symbol' => 'Fr',
    'language' => 'de',
    'language_name' => 'Deutsch',
    'country_code' => '423',
    'timezone' => 'UTC+01:00',
  ],
  'lt' => 
  [
    'name' => 'Lithuania',
    'capital' => 'Vilnius',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'lt',
    'language_name' => 'lietuvių kalba',
    'country_code' => '370',
    'timezone' => 'UTC+02:00',
  ],
  'lu' => 
  [
    'name' => 'Luxembourg',
    'capital' => 'Luxembourg',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '352',
    'timezone' => 'UTC+01:00',
  ],
  'mo' => 
  [
    'name' => 'Macao',
    'capital' => '',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'MOP',
    'currency_symbol' => 'P',
    'language' => 'zh',
    'language_name' => '中文 (Zhōngwén]',
    'country_code' => '853',
    'timezone' => 'UTC+08:00',
  ],
  'mk' => 
  [
    'name' => 'Macedonia (the former Yugoslav Republic of]',
    'capital' => 'Skopje',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'MKD',
    'currency_symbol' => 'ден',
    'language' => 'mk',
    'language_name' => 'македонски јазик',
    'country_code' => '389',
    'timezone' => 'UTC+01:00',
  ],
  'mg' => 
  [
    'name' => 'Madagascar',
    'capital' => 'Antananarivo',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'MGA',
    'currency_symbol' => 'Ar',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '261',
    'timezone' => 'UTC+03:00',
  ],
  'mw' => 
  [
    'name' => 'Malawi',
    'capital' => 'Lilongwe',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'MWK',
    'currency_symbol' => 'MK',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '265',
    'timezone' => 'UTC+02:00',
  ],
  'my' => 
  [
    'name' => 'Malaysia',
    'capital' => 'Kuala Lumpur',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'MYR',
    'currency_symbol' => 'RM',
    'language' => NULL,
    'language_name' => 'بهاس مليسيا',
    'country_code' => '60',
    'timezone' => 'UTC+08:00',
  ],
  'mv' => 
  [
    'name' => 'Maldives',
    'capital' => 'Malé',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'MVR',
    'currency_symbol' => '.ރ',
    'language' => 'dv',
    'language_name' => 'ދިވެހި',
    'country_code' => '960',
    'timezone' => 'UTC+05:00',
  ],
  'ml' => 
  [
    'name' => 'Mali',
    'capital' => 'Bamako',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '223',
    'timezone' => 'UTC',
  ],
  'mt' => 
  [
    'name' => 'Malta',
    'capital' => 'Valletta',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'mt',
    'language_name' => 'Malti',
    'country_code' => '356',
    'timezone' => 'UTC+01:00',
  ],
  'mh' => 
  [
    'name' => 'Marshall Islands',
    'capital' => 'Majuro',
    'region' => 'Oceania',
    'subregion' => 'Micronesia',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '692',
    'timezone' => 'UTC+12:00',
  ],
  'mq' => 
  [
    'name' => 'Martinique',
    'capital' => 'Fort-de-France',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '596',
    'timezone' => 'UTC-04:00',
  ],
  'mr' => 
  [
    'name' => 'Mauritania',
    'capital' => 'Nouakchott',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'MRO',
    'currency_symbol' => 'UM',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '222',
    'timezone' => 'UTC',
  ],
  'mu' => 
  [
    'name' => 'Mauritius',
    'capital' => 'Port Louis',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'MUR',
    'currency_symbol' => '₨',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '230',
    'timezone' => 'UTC+04:00',
  ],
  'yt' => 
  [
    'name' => 'Mayotte',
    'capital' => 'Mamoudzou',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '262',
    'timezone' => 'UTC+03:00',
  ],
  'mx' => 
  [
    'name' => 'Mexico',
    'capital' => 'Mexico City',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'MXN',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '52',
    'timezone' => 'UTC-08:00',
  ],
  'fm' => 
  [
    'name' => 'Micronesia (Federated States of]',
    'capital' => 'Palikir',
    'region' => 'Oceania',
    'subregion' => 'Micronesia',
    'currency' => NULL,
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '691',
    'timezone' => 'UTC+10:00',
  ],
  'md' => 
  [
    'name' => 'Moldova (Republic of]',
    'capital' => 'Chișinău',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'MDL',
    'currency_symbol' => 'L',
    'language' => 'ro',
    'language_name' => 'Română',
    'country_code' => '373',
    'timezone' => 'UTC+02:00',
  ],
  'mc' => 
  [
    'name' => 'Monaco',
    'capital' => 'Monaco',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '377',
    'timezone' => 'UTC+01:00',
  ],
  'mn' => 
  [
    'name' => 'Mongolia',
    'capital' => 'Ulan Bator',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'MNT',
    'currency_symbol' => '₮',
    'language' => 'mn',
    'language_name' => 'Монгол хэл',
    'country_code' => '976',
    'timezone' => 'UTC+07:00',
  ],
  'me' => 
  [
    'name' => 'Montenegro',
    'capital' => 'Podgorica',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'sr',
    'language_name' => 'српски језик',
    'country_code' => '382',
    'timezone' => 'UTC+01:00',
  ],
  'ms' => 
  [
    'name' => 'Montserrat',
    'capital' => 'Plymouth',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1664',
    'timezone' => 'UTC-04:00',
  ],
  'ma' => 
  [
    'name' => 'Morocco',
    'capital' => 'Rabat',
    'region' => 'Africa',
    'subregion' => 'Northern Africa',
    'currency' => 'MAD',
    'currency_symbol' => 'د.م.',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '212',
    'timezone' => 'UTC',
  ],
  'mz' => 
  [
    'name' => 'Mozambique',
    'capital' => 'Maputo',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'MZN',
    'currency_symbol' => 'MT',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '258',
    'timezone' => 'UTC+02:00',
  ],
  'mm' => 
  [
    'name' => 'Myanmar',
    'capital' => 'Naypyidaw',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'MMK',
    'currency_symbol' => 'Ks',
    'language' => 'my',
    'language_name' => 'ဗမာစာ',
    'country_code' => '95',
    'timezone' => 'UTC+06:30',
  ],
  'na' => 
  [
    'name' => 'Namibia',
    'capital' => 'Windhoek',
    'region' => 'Africa',
    'subregion' => 'Southern Africa',
    'currency' => 'NAD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '264',
    'timezone' => 'UTC+01:00',
  ],
  'nr' => 
  [
    'name' => 'Nauru',
    'capital' => 'Yaren',
    'region' => 'Oceania',
    'subregion' => 'Micronesia',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '674',
    'timezone' => 'UTC+12:00',
  ],
  'np' => 
  [
    'name' => 'Nepal',
    'capital' => 'Kathmandu',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'NPR',
    'currency_symbol' => '₨',
    'language' => 'ne',
    'language_name' => 'नेपाली',
    'country_code' => '977',
    'timezone' => 'UTC+05:45',
  ],
  'nl' => 
  [
    'name' => 'Netherlands',
    'capital' => 'Amsterdam',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'nl',
    'language_name' => 'Nederlands',
    'country_code' => '31',
    'timezone' => 'UTC-04:00',
  ],
  'nc' => 
  [
    'name' => 'New Caledonia',
    'capital' => 'Nouméa',
    'region' => 'Oceania',
    'subregion' => 'Melanesia',
    'currency' => 'XPF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '687',
    'timezone' => 'UTC+11:00',
  ],
  'nz' => 
  [
    'name' => 'New Zealand',
    'capital' => 'Wellington',
    'region' => 'Oceania',
    'subregion' => 'Australia and New Zealand',
    'currency' => 'NZD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '64',
    'timezone' => 'UTC-11:00',
  ],
  'ni' => 
  [
    'name' => 'Nicaragua',
    'capital' => 'Managua',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'NIO',
    'currency_symbol' => 'C$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '505',
    'timezone' => 'UTC-06:00',
  ],
  'ne' => 
  [
    'name' => 'Niger',
    'capital' => 'Niamey',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '227',
    'timezone' => 'UTC+01:00',
  ],
  'ng' => 
  [
    'name' => 'Nigeria',
    'capital' => 'Abuja',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'NGN',
    'currency_symbol' => '₦',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '234',
    'timezone' => 'UTC+01:00',
  ],
  'nu' => 
  [
    'name' => 'Niue',
    'capital' => 'Alofi',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'NZD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '683',
    'timezone' => 'UTC-11:00',
  ],
  'nf' => 
  [
    'name' => 'Norfolk Island',
    'capital' => 'Kingston',
    'region' => 'Oceania',
    'subregion' => 'Australia and New Zealand',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '672',
    'timezone' => 'UTC+11:30',
  ],
  'kp' => 
  [
    'name' => 'Korea (Democratic People\'s Republic of]',
    'capital' => 'Pyongyang',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'KPW',
    'currency_symbol' => '₩',
    'language' => 'ko',
    'language_name' => '한국어',
    'country_code' => '850',
    'timezone' => 'UTC+09:00',
  ],
  'mp' => 
  [
    'name' => 'Northern Mariana Islands',
    'capital' => 'Saipan',
    'region' => 'Oceania',
    'subregion' => 'Micronesia',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1670',
    'timezone' => 'UTC+10:00',
  ],
  'no' => 
  [
    'name' => 'Norway',
    'capital' => 'Oslo',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'NOK',
    'currency_symbol' => 'kr',
    'language' => 'no',
    'language_name' => 'Norsk',
    'country_code' => '47',
    'timezone' => 'UTC+01:00',
  ],
  'om' => 
  [
    'name' => 'Oman',
    'capital' => 'Muscat',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'OMR',
    'currency_symbol' => 'ر.ع.',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '968',
    'timezone' => 'UTC+04:00',
  ],
  'pk' => 
  [
    'name' => 'Pakistan',
    'capital' => 'Islamabad',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'PKR',
    'currency_symbol' => '₨',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '92',
    'timezone' => 'UTC+05:00',
  ],
  'pw' => 
  [
    'name' => 'Palau',
    'capital' => 'Ngerulmud',
    'region' => 'Oceania',
    'subregion' => 'Micronesia',
    'currency' => '(none]',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '680',
    'timezone' => 'UTC+09:00',
  ],
  'ps' => 
  [
    'name' => 'Palestine, State of',
    'capital' => 'Ramallah',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'ILS',
    'currency_symbol' => '₪',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '970',
    'timezone' => 'UTC+02:00',
  ],
  'pa' => 
  [
    'name' => 'Panama',
    'capital' => 'Panama City',
    'region' => 'Americas',
    'subregion' => 'Central America',
    'currency' => 'PAB',
    'currency_symbol' => 'B/.',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '507',
    'timezone' => 'UTC-05:00',
  ],
  'pg' => 
  [
    'name' => 'Papua New Guinea',
    'capital' => 'Port Moresby',
    'region' => 'Oceania',
    'subregion' => 'Melanesia',
    'currency' => 'PGK',
    'currency_symbol' => 'K',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '675',
    'timezone' => 'UTC+10:00',
  ],
  'py' => 
  [
    'name' => 'Paraguay',
    'capital' => 'Asunción',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'PYG',
    'currency_symbol' => '₲',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '595',
    'timezone' => 'UTC-04:00',
  ],
  'pe' => 
  [
    'name' => 'Peru',
    'capital' => 'Lima',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'PEN',
    'currency_symbol' => 'S/.',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '51',
    'timezone' => 'UTC-05:00',
  ],
  'ph' => 
  [
    'name' => 'Philippines',
    'capital' => 'Manila',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'PHP',
    'currency_symbol' => '₱',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '63',
    'timezone' => 'UTC+08:00',
  ],
  'pn' => 
  [
    'name' => 'Pitcairn',
    'capital' => 'Adamstown',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'NZD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '64',
    'timezone' => 'UTC-08:00',
  ],
  'pl' => 
  [
    'name' => 'Poland',
    'capital' => 'Warsaw',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'PLN',
    'currency_symbol' => 'zł',
    'language' => 'pl',
    'language_name' => 'język polski',
    'country_code' => '48',
    'timezone' => 'UTC+01:00',
  ],
  'pt' => 
  [
    'name' => 'Portugal',
    'capital' => 'Lisbon',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '351',
    'timezone' => 'UTC-01:00',
  ],
  'pr' => 
  [
    'name' => 'Puerto Rico',
    'capital' => 'San Juan',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '1787',
    'timezone' => 'UTC-04:00',
  ],
  'qa' => 
  [
    'name' => 'Qatar',
    'capital' => 'Doha',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'QAR',
    'currency_symbol' => 'ر.ق',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '974',
    'timezone' => 'UTC+03:00',
  ],
  'xk' => 
  [
    'name' => 'Republic of Kosovo',
    'capital' => 'Pristina',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'sq',
    'language_name' => 'Shqip',
    'country_code' => '383',
    'timezone' => 'UTC+01:00',
  ],
  're' => 
  [
    'name' => 'Réunion',
    'capital' => 'Saint-Denis',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '262',
    'timezone' => 'UTC+04:00',
  ],
  'ro' => 
  [
    'name' => 'Romania',
    'capital' => 'Bucharest',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'RON',
    'currency_symbol' => 'lei',
    'language' => 'ro',
    'language_name' => 'Română',
    'country_code' => '40',
    'timezone' => 'UTC+02:00',
  ],
  'ru' => 
  [
    'name' => 'Russian Federation',
    'capital' => 'Moscow',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'RUB',
    'currency_symbol' => '₽',
    'language' => 'ru',
    'language_name' => 'Русский',
    'country_code' => '7',
    'timezone' => 'UTC+03:00',
  ],
  'rw' => 
  [
    'name' => 'Rwanda',
    'capital' => 'Kigali',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'RWF',
    'currency_symbol' => 'Fr',
    'language' => 'rw',
    'language_name' => 'Ikinyarwanda',
    'country_code' => '250',
    'timezone' => 'UTC+02:00',
  ],
  'bl' => 
  [
    'name' => 'Saint Barthélemy',
    'capital' => 'Gustavia',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '590',
    'timezone' => 'UTC-04:00',
  ],
  'sh' => 
  [
    'name' => 'Saint Helena, Ascension and Tristan da Cunha',
    'capital' => 'Jamestown',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'SHP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '290',
    'timezone' => 'UTC+00:00',
  ],
  'kn' => 
  [
    'name' => 'Saint Kitts and Nevis',
    'capital' => 'Basseterre',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1869',
    'timezone' => 'UTC-04:00',
  ],
  'lc' => 
  [
    'name' => 'Saint Lucia',
    'capital' => 'Castries',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1758',
    'timezone' => 'UTC-04:00',
  ],
  'mf' => 
  [
    'name' => 'Saint Martin (French part]',
    'capital' => 'Marigot',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '590',
    'timezone' => 'UTC-04:00',
  ],
  'pm' => 
  [
    'name' => 'Saint Pierre and Miquelon',
    'capital' => 'Saint-Pierre',
    'region' => 'Americas',
    'subregion' => 'Northern America',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '508',
    'timezone' => 'UTC-03:00',
  ],
  'vc' => 
  [
    'name' => 'Saint Vincent and the Grenadines',
    'capital' => 'Kingstown',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'XCD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1784',
    'timezone' => 'UTC-04:00',
  ],
  'ws' => 
  [
    'name' => 'Samoa',
    'capital' => 'Apia',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'WST',
    'currency_symbol' => 'T',
    'language' => 'sm',
    'language_name' => 'gagana fa\'a Samoa',
    'country_code' => '685',
    'timezone' => 'UTC+13:00',
  ],
  'sm' => 
  [
    'name' => 'San Marino',
    'capital' => 'City of San Marino',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'it',
    'language_name' => 'Italiano',
    'country_code' => '378',
    'timezone' => 'UTC+01:00',
  ],
  'st' => 
  [
    'name' => 'Sao Tome and Principe',
    'capital' => 'São Tomé',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'STD',
    'currency_symbol' => 'Db',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '239',
    'timezone' => 'UTC',
  ],
  'sa' => 
  [
    'name' => 'Saudi Arabia',
    'capital' => 'Riyadh',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'SAR',
    'currency_symbol' => 'ر.س',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '966',
    'timezone' => 'UTC+03:00',
  ],
  'sn' => 
  [
    'name' => 'Senegal',
    'capital' => 'Dakar',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '221',
    'timezone' => 'UTC',
  ],
  'rs' => 
  [
    'name' => 'Serbia',
    'capital' => 'Belgrade',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'RSD',
    'currency_symbol' => 'дин.',
    'language' => 'sr',
    'language_name' => 'српски језик',
    'country_code' => '381',
    'timezone' => 'UTC+01:00',
  ],
  'sc' => 
  [
    'name' => 'Seychelles',
    'capital' => 'Victoria',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'SCR',
    'currency_symbol' => '₨',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '248',
    'timezone' => 'UTC+04:00',
  ],
  'sl' => 
  [
    'name' => 'Sierra Leone',
    'capital' => 'Freetown',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'SLL',
    'currency_symbol' => 'Le',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '232',
    'timezone' => 'UTC',
  ],
  'sg' => 
  [
    'name' => 'Singapore',
    'capital' => 'Singapore',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'BND',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '65',
    'timezone' => 'UTC+08:00',
  ],
  'sx' => 
  [
    'name' => 'Sint Maarten (Dutch part]',
    'capital' => 'Philipsburg',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'ANG',
    'currency_symbol' => 'ƒ',
    'language' => 'nl',
    'language_name' => 'Nederlands',
    'country_code' => '1721',
    'timezone' => 'UTC-04:00',
  ],
  'sk' => 
  [
    'name' => 'Slovakia',
    'capital' => 'Bratislava',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'sk',
    'language_name' => 'slovenčina',
    'country_code' => '421',
    'timezone' => 'UTC+01:00',
  ],
  'si' => 
  [
    'name' => 'Slovenia',
    'capital' => 'Ljubljana',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'sl',
    'language_name' => 'slovenski jezik',
    'country_code' => '386',
    'timezone' => 'UTC+01:00',
  ],
  'sb' => 
  [
    'name' => 'Solomon Islands',
    'capital' => 'Honiara',
    'region' => 'Oceania',
    'subregion' => 'Melanesia',
    'currency' => 'SBD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '677',
    'timezone' => 'UTC+11:00',
  ],
  'so' => 
  [
    'name' => 'Somalia',
    'capital' => 'Mogadishu',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'SOS',
    'currency_symbol' => 'Sh',
    'language' => 'so',
    'language_name' => 'Soomaaliga',
    'country_code' => '252',
    'timezone' => 'UTC+03:00',
  ],
  'za' => 
  [
    'name' => 'South Africa',
    'capital' => 'Pretoria',
    'region' => 'Africa',
    'subregion' => 'Southern Africa',
    'currency' => 'ZAR',
    'currency_symbol' => 'R',
    'language' => 'af',
    'language_name' => 'Afrikaans',
    'country_code' => '27',
    'timezone' => 'UTC+02:00',
  ],
  'gs' => 
  [
    'name' => 'South Georgia and the South Sandwich Islands',
    'capital' => 'King Edward Point',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'GBP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '500',
    'timezone' => 'UTC-02:00',
  ],
  'kr' => 
  [
    'name' => 'Korea (Republic of]',
    'capital' => 'Seoul',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'KRW',
    'currency_symbol' => '₩',
    'language' => 'ko',
    'language_name' => '한국어',
    'country_code' => '82',
    'timezone' => 'UTC+09:00',
  ],
  'ss' => 
  [
    'name' => 'South Sudan',
    'capital' => 'Juba',
    'region' => 'Africa',
    'subregion' => 'Middle Africa',
    'currency' => 'SSP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '211',
    'timezone' => 'UTC+03:00',
  ],
  'es' => 
  [
    'name' => 'Spain',
    'capital' => 'Madrid',
    'region' => 'Europe',
    'subregion' => 'Southern Europe',
    'currency' => 'EUR',
    'currency_symbol' => '€',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '34',
    'timezone' => 'UTC',
  ],
  'lk' => 
  [
    'name' => 'Sri Lanka',
    'capital' => 'Colombo',
    'region' => 'Asia',
    'subregion' => 'Southern Asia',
    'currency' => 'LKR',
    'currency_symbol' => 'Rs',
    'language' => 'si',
    'language_name' => 'සිංහල',
    'country_code' => '94',
    'timezone' => 'UTC+05:30',
  ],
  'sd' => 
  [
    'name' => 'Sudan',
    'capital' => 'Khartoum',
    'region' => 'Africa',
    'subregion' => 'Northern Africa',
    'currency' => 'SDG',
    'currency_symbol' => 'ج.س.',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '249',
    'timezone' => 'UTC+03:00',
  ],
  'sr' => 
  [
    'name' => 'Suriname',
    'capital' => 'Paramaribo',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'SRD',
    'currency_symbol' => '$',
    'language' => 'nl',
    'language_name' => 'Nederlands',
    'country_code' => '597',
    'timezone' => 'UTC-03:00',
  ],
  'sj' => 
  [
    'name' => 'Svalbard and Jan Mayen',
    'capital' => 'Longyearbyen',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'NOK',
    'currency_symbol' => 'kr',
    'language' => 'no',
    'language_name' => 'Norsk',
    'country_code' => '4779',
    'timezone' => 'UTC+01:00',
  ],
  'sz' => 
  [
    'name' => 'Swaziland',
    'capital' => 'Lobamba',
    'region' => 'Africa',
    'subregion' => 'Southern Africa',
    'currency' => 'SZL',
    'currency_symbol' => 'L',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '268',
    'timezone' => 'UTC+02:00',
  ],
  'se' => 
  [
    'name' => 'Sweden',
    'capital' => 'Stockholm',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'SEK',
    'currency_symbol' => 'kr',
    'language' => 'sv',
    'language_name' => 'svenska',
    'country_code' => '46',
    'timezone' => 'UTC+01:00',
  ],
  'ch' => 
  [
    'name' => 'Switzerland',
    'capital' => 'Bern',
    'region' => 'Europe',
    'subregion' => 'Western Europe',
    'currency' => 'CHF',
    'currency_symbol' => 'Fr',
    'language' => 'de',
    'language_name' => 'Deutsch',
    'country_code' => '41',
    'timezone' => 'UTC+01:00',
  ],
  'sy' => 
  [
    'name' => 'Syrian Arab Republic',
    'capital' => 'Damascus',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'SYP',
    'currency_symbol' => '£',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '963',
    'timezone' => 'UTC+02:00',
  ],
  'tw' => 
  [
    'name' => 'Taiwan',
    'capital' => 'Taipei',
    'region' => 'Asia',
    'subregion' => 'Eastern Asia',
    'currency' => 'TWD',
    'currency_symbol' => '$',
    'language' => 'zh',
    'language_name' => '中文 (Zhōngwén]',
    'country_code' => '886',
    'timezone' => 'UTC+08:00',
  ],
  'tj' => 
  [
    'name' => 'Tajikistan',
    'capital' => 'Dushanbe',
    'region' => 'Asia',
    'subregion' => 'Central Asia',
    'currency' => 'TJS',
    'currency_symbol' => 'ЅМ',
    'language' => 'tg',
    'language_name' => 'тоҷикӣ',
    'country_code' => '992',
    'timezone' => 'UTC+05:00',
  ],
  'tz' => 
  [
    'name' => 'Tanzania, United Republic of',
    'capital' => 'Dodoma',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'TZS',
    'currency_symbol' => 'Sh',
    'language' => 'sw',
    'language_name' => 'Kiswahili',
    'country_code' => '255',
    'timezone' => 'UTC+03:00',
  ],
  'th' => 
  [
    'name' => 'Thailand',
    'capital' => 'Bangkok',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'THB',
    'currency_symbol' => '฿',
    'language' => 'th',
    'language_name' => 'ไทย',
    'country_code' => '66',
    'timezone' => 'UTC+07:00',
  ],
  'tl' => 
  [
    'name' => 'Timor-Leste',
    'capital' => 'Dili',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'pt',
    'language_name' => 'Português',
    'country_code' => '670',
    'timezone' => 'UTC+09:00',
  ],
  'tg' => 
  [
    'name' => 'Togo',
    'capital' => 'Lomé',
    'region' => 'Africa',
    'subregion' => 'Western Africa',
    'currency' => 'XOF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '228',
    'timezone' => 'UTC',
  ],
  'tk' => 
  [
    'name' => 'Tokelau',
    'capital' => 'Fakaofo',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'NZD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '690',
    'timezone' => 'UTC+13:00',
  ],
  'to' => 
  [
    'name' => 'Tonga',
    'capital' => 'Nuku\'alofa',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'TOP',
    'currency_symbol' => 'T$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '676',
    'timezone' => 'UTC+13:00',
  ],
  'tt' => 
  [
    'name' => 'Trinidad and Tobago',
    'capital' => 'Port of Spain',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'TTD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1868',
    'timezone' => 'UTC-04:00',
  ],
  'tn' => 
  [
    'name' => 'Tunisia',
    'capital' => 'Tunis',
    'region' => 'Africa',
    'subregion' => 'Northern Africa',
    'currency' => 'TND',
    'currency_symbol' => 'د.ت',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '216',
    'timezone' => 'UTC+01:00',
  ],
  'tr' => 
  [
    'name' => 'Turkey',
    'capital' => 'Ankara',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'TRY',
    'currency_symbol' => NULL,
    'language' => 'tr',
    'language_name' => 'Türkçe',
    'country_code' => '90',
    'timezone' => 'UTC+03:00',
  ],
  'tm' => 
  [
    'name' => 'Turkmenistan',
    'capital' => 'Ashgabat',
    'region' => 'Asia',
    'subregion' => 'Central Asia',
    'currency' => 'TMT',
    'currency_symbol' => 'm',
    'language' => 'tk',
    'language_name' => 'Türkmen',
    'country_code' => '993',
    'timezone' => 'UTC+05:00',
  ],
  'tc' => 
  [
    'name' => 'Turks and Caicos Islands',
    'capital' => 'Cockburn Town',
    'region' => 'Americas',
    'subregion' => 'Caribbean',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1649',
    'timezone' => 'UTC-04:00',
  ],
  'tv' => 
  [
    'name' => 'Tuvalu',
    'capital' => 'Funafuti',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'AUD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '688',
    'timezone' => 'UTC+12:00',
  ],
  'ug' => 
  [
    'name' => 'Uganda',
    'capital' => 'Kampala',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'UGX',
    'currency_symbol' => 'Sh',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '256',
    'timezone' => 'UTC+03:00',
  ],
  'ua' => 
  [
    'name' => 'Ukraine',
    'capital' => 'Kiev',
    'region' => 'Europe',
    'subregion' => 'Eastern Europe',
    'currency' => 'UAH',
    'currency_symbol' => '₴',
    'language' => 'uk',
    'language_name' => 'Українська',
    'country_code' => '380',
    'timezone' => 'UTC+02:00',
  ],
  'ae' => 
  [
    'name' => 'United Arab Emirates',
    'capital' => 'Abu Dhabi',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'AED',
    'currency_symbol' => 'د.إ',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '971',
    'timezone' => 'UTC+04',
  ],
  'gb' => 
  [
    'name' => 'United Kingdom of Great Britain and Northern Ireland',
    'capital' => 'London',
    'region' => 'Europe',
    'subregion' => 'Northern Europe',
    'currency' => 'GBP',
    'currency_symbol' => '£',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '44',
    'timezone' => 'UTC-08:00',
  ],
  'us' => 
  [
    'name' => 'United States of America',
    'capital' => 'Washington, D.C.',
    'region' => 'Americas',
    'subregion' => 'Northern America',
    'currency' => 'USD',
    'currency_symbol' => '$',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '1',
    'timezone' => 'UTC-12:00',
  ],
  'uy' => 
  [
    'name' => 'Uruguay',
    'capital' => 'Montevideo',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'UYU',
    'currency_symbol' => '$',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '598',
    'timezone' => 'UTC-03:00',
  ],
  'uz' => 
  [
    'name' => 'Uzbekistan',
    'capital' => 'Tashkent',
    'region' => 'Asia',
    'subregion' => 'Central Asia',
    'currency' => 'UZS',
    'currency_symbol' => NULL,
    'language' => 'uz',
    'language_name' => 'Oʻzbek',
    'country_code' => '998',
    'timezone' => 'UTC+05:00',
  ],
  'vu' => 
  [
    'name' => 'Vanuatu',
    'capital' => 'Port Vila',
    'region' => 'Oceania',
    'subregion' => 'Melanesia',
    'currency' => 'VUV',
    'currency_symbol' => 'Vt',
    'language' => 'bi',
    'language_name' => 'Bislama',
    'country_code' => '678',
    'timezone' => 'UTC+11:00',
  ],
  've' => 
  [
    'name' => 'Venezuela (Bolivarian Republic of]',
    'capital' => 'Caracas',
    'region' => 'Americas',
    'subregion' => 'South America',
    'currency' => 'VEF',
    'currency_symbol' => 'Bs F',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '58',
    'timezone' => 'UTC-04:00',
  ],
  'vn' => 
  [
    'name' => 'Viet Nam',
    'capital' => 'Hanoi',
    'region' => 'Asia',
    'subregion' => 'South-Eastern Asia',
    'currency' => 'VND',
    'currency_symbol' => '₫',
    'language' => 'vi',
    'language_name' => 'Tiếng Việt',
    'country_code' => '84',
    'timezone' => 'UTC+07:00',
  ],
  'wf' => 
  [
    'name' => 'Wallis and Futuna',
    'capital' => 'Mata-Utu',
    'region' => 'Oceania',
    'subregion' => 'Polynesia',
    'currency' => 'XPF',
    'currency_symbol' => 'Fr',
    'language' => 'fr',
    'language_name' => 'français',
    'country_code' => '681',
    'timezone' => 'UTC+12:00',
  ],
  'eh' => 
  [
    'name' => 'Western Sahara',
    'capital' => 'El Aaiún',
    'region' => 'Africa',
    'subregion' => 'Northern Africa',
    'currency' => 'MAD',
    'currency_symbol' => 'د.م.',
    'language' => 'es',
    'language_name' => 'Español',
    'country_code' => '212',
    'timezone' => 'UTC+00:00',
  ],
  'ye' => 
  [
    'name' => 'Yemen',
    'capital' => 'Sana\'a',
    'region' => 'Asia',
    'subregion' => 'Western Asia',
    'currency' => 'YER',
    'currency_symbol' => '﷼',
    'language' => 'ar',
    'language_name' => 'العربية',
    'country_code' => '967',
    'timezone' => 'UTC+03:00',
  ],
  'zm' => 
  [
    'name' => 'Zambia',
    'capital' => 'Lusaka',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'ZMW',
    'currency_symbol' => 'ZK',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '260',
    'timezone' => 'UTC+02:00',
  ],
  'zw' => 
  [
    'name' => 'Zimbabwe',
    'capital' => 'Harare',
    'region' => 'Africa',
    'subregion' => 'Eastern Africa',
    'currency' => 'BWP',
    'currency_symbol' => 'P',
    'language' => 'en',
    'language_name' => 'English',
    'country_code' => '263',
    'timezone' => 'UTC+02:00',
  ],
]; ?>