<?php

namespace backend\modules\system\models;

use common\base\BaseAPIObject;
use common\components\FApi;

/**
 * This is the model class for table "object_banner".
 *
 * @property integer $id
 * @property integer $object_id
 * @property string $object_type
 * @property string $image
 * @property string $title
 * @property string $link_url
 * @property string $platform
 * @property string $position
 * @property string $type
 * @property integer $sort_order
 * @property integer $is_active
 * @property string $application_id
 */
class ObjectBannerAPI extends BaseAPIObject
{
    const PLATFORM_ANDROID = 'android';
    const PLATFORM_IOS = 'ios';
    const PLATFORM_WEB = 'web';
    const POSITION_DASHBOARD = 'dashboard';
    const PLATFORM_ALL = 'all';
    const POSITION_TOP = 'top';
    const POSITION_BOTTOM = 'bottom';
    const POSITION_LEFT = 'left';
    const POSITION_RIGHT = 'right';
    const POSITION_CENTER = 'center';
    const POSITION_MIDDLE = 'middle';
    const TYPE_BANNER = 'banner';
    const TYPE_BLOCK = 'block';
    const TYPE_VERTICAL = 'vertical';
    const TYPE_HORIZONTAL = 'horizontal';
    const TYPE_FULL_SCREEN = 'full-screen';

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        $folder = 'object-banner';
        $image = FApi::getImageUrlForAPI($this->image, $folder);
        $this->image = $image;
        return $fields;
    }

    public function getApiFields()
    {
        //$fields = parent::getApiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'object_id',
            'object_type',
            'image',
            'title',
            'link_url',
            'platform',
            'position',
            'type'
        ];
        return $fields;
    }
}