<?php

namespace backend\modules\system\models;

use common\base\BaseAPIObject;

/**
 * @property string $id
 * @property string $object_id
 * @property string $object_type
 * @property string $parent_id
 * @property string $name
 * @property string $email
 * @property string $title
 * @property string $content
 * @property integer $user_id
 * @property string $user_type
 * @property string $user_role
 * @property integer $like_count
 * @property integer $dislike_count
 * @property integer $share_count
 * @property integer $reply_count
 * @property string $type
 * @property integer $is_active
 * @property string $created_date
 * @property string $modified_date
 * @property string $application_id
 *
 * @property ObjectCommentAPI[] $replies
 *
 */
class ObjectCommentAPI extends BaseAPIObject
{
    //Overwrite if model class not include table name
    public static function tableName()
    {
        return 'object_comment';
    }
    //Set value for output
    public function fields()
    {
        $fields = parent::fields();
        return $fields;
    }
    //All fields for validate input
    public function getApiFields()
    {
        $fields = parent::getApiFields(); // TODO: Change the autogenerated stub
        $fields = array_merge($fields, ['replies']);
        return $fields;
    }
    //Relations
    public function getReplies()
    {
        return $this->hasMany(ObjectCommentAPI::className(), ['parent_id' => 'id']);
    }
}