<?php

namespace backend\modules\system\models;

use common\base\BaseAPIObject;

/**
 * This is the model class for table "object_review".
 *
 * @property integer $id
 * @property integer $object_id
 * @property string $object_type
 * @property string $name
 * @property string $email
 * @property double $rate
 * @property string $title
 * @property string $content
 * @property integer $user_id
 * @property string $user_type
 * @property string $user_role
 * @property integer $like_count
 * @property integer $dislike_count
 * @property integer $share_count
 * @property integer $comment_count
 * @property string $type
 * @property integer $is_active
 * @property string $created_date
 * @property string $modified_date
 * @property string $application_id
 */
class ObjectReviewAPI extends BaseAPIObject
{
    const USER_TYPE_APP_USER = 'app_user';
    const USER_TYPE_USER = 'user';

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function getApiFields()
    {
        //$fields = parent::getApiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'object_id',
            'object_type',
            'name',
            'email',
            'rate',
            'title',
            'content',
            'user_id',
            'user_type',
            'user_role',
            'like_count',
            'dislike_count',
            'share_count',
            'comment_count',
            'type'
        ];
        return $fields;
    }
}