<?php

namespace backend\modules\system\models;

use common\base\BaseAPIObject;

/**
 * This is the model class for table "object_activity".
 *
 * @property integer $id
 * @property string $object_id
 * @property string $object_type
 * @property string $type
 * @property integer $user_id
 * @property string $user_type
 * @property string $created_date
 * @property string $modified_date
 * @property string $application_id
 */
class ObjectActivityAPI extends BaseAPIObject
{
    const TYPE_LIKE = 'like';
    const TYPE_SHARE = 'share';
    const TYPE_FAVOURITE = 'favourite';
    const TYPE_RATE = 'rate';
    const USER_TYPE_APP_USER = 'app_user';
    const USER_TYPE_USER = 'user';

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function getApiFields()
    {
        //$fields = parent::getApiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'object_id',
            'object_type',
            'type',
            'user_id',
            'user_type'
        ];
        return $fields;
    }
}