<?php

namespace backend\modules\system\models;

use common\base\BaseAPIObject;
use common\components\FApi;

/**
 * This is the model class for table "object_counter_history".
 *
 * @property integer $id
 * @property integer $object_id
 * @property string $object_type
 * @property integer $count
 * @property string $attribute
 * @property string $date
 * @property string $week
 * @property string $month
 * @property string $year
 * @property string $focus
 * @property integer $position
 * @property string $type
 */
class ObjectCounterHistoryAPI extends BaseAPIObject
{
    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        //$folder = 'object-counter-history';
        //$image = FApi::getImageUrlForAPI($this->image, $folder);
        //$this->image = $image;
        return $fields;
    }

    public function getApiFields()
    {
        //$fields = parent::getApiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'object_id',
            'object_type',
            'count',
            'attribute',
            'date',
            'week',
            'month',
            'year',
            'focus',
            'position',
            'type'
        ];
        return $fields;
    }
}