<?php
/**
 * Created by PhpStorm.
 * User: Quan
 * Date: 12/07/2017
 * Time: 17:24 CH
 */

namespace common\widgets\fsocialshare;

use common\widgets\BaseWidget;

class FComment extends  BaseWidget
{
    public $width;
    public $numposts;
    public $url;
    protected function prepareData()
    {
        $this->page_code = !empty($this->page_code) ? $this->page_code : 'common';
        $this->show_headline = false;
        $this->display_type = !empty($this->display_type) ? $this->display_type : 'comment_disqus.php';
        parent::prepareData();  // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();
        return $this->render($this->display_type ,
            [
                'width' => $this->width,
                'numposts' => $this->numposts,
                'url' => $this->url
            ]);
    }
}
?>