<?php
/**
 * Created by PhpStorm.
 * User: Quan
 * Date: 12/07/2017
 * Time: 21:37 CH
 */

namespace common\widgets\fsocialshare;

use common\widgets\BaseWidget;

class FConnectFb extends  BaseWidget
{
    public $appID;
    public $lang;
    protected function prepareData()
    {
        $this->page_code = !empty($this->page_code) ? $this->page_code : 'common';
        $this->show_headline = false;

        $this->display_type = !empty($this->display_type) ? $this->display_type : 'connect_fb.php';
        parent::prepareData();  // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();
        return $this->render($this->display_type ,
            [
                'appID' => $this->appID,
                'lang' => $this->lang
            ]);
    }
}

?>