<?php
namespace common\widgets\fsocialshare;

use common\components\FConfig;
use common\widgets\BaseWidget;

class FGoogleAnalytic extends BaseWidget
{
    public $google_analytic_key;

    protected function prepareData()
    {
        $this->page_code = !empty($this->page_code) ? $this->page_code : 'common';
        $this->show_headline = false;

        $this->display_type = !empty($this->display_type) ? $this->display_type : 'google_analytic.php';

        parent::prepareData(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();

        if (!isset($this->google_analytic_key))
            $this->google_analytic_key = FConfig::setting('google_analytic_key');

        if (empty($this->google_analytic_key))
            return '';

        return $this->render($this->display_type ,
            [
                'google_analytic_key' => $this->google_analytic_key,
            ]);
    }
}

?>