<?php
namespace common\widgets\fsocialshare;

use common\components\FConfig;
use common\widgets\BaseWidget;

class FGoogleAdwords extends BaseWidget
{
    public $google_adwords_key;

    protected function prepareData()
    {
        $this->page_code = !empty($this->page_code) ? $this->page_code : 'common';
        $this->show_headline = false;

        $this->display_type = !empty($this->display_type) ? $this->display_type : 'google_adwords.php';

        parent::prepareData(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        self::prepareData();

        if (!isset($this->google_adwords_key))
            $this->google_adwords_key = FConfig::setting('google_adwords_key');

        if (empty($this->google_adwords_key))
            return '';

        return $this->render($this->display_type ,
            [
                'google_adwords_key' => $this->google_adwords_key,
            ]);
    }
}

?>