<?php

namespace backend\models;

use common\base\BaseAPIObject;

/**
 * This is the model class for table "object_relation".
 *
 * @property string $id
 * @property string $object_id
 * @property string $object_type
 * @property string $object2_id
 * @property string $object2_type
 * @property string $relation_type
 * @property integer $sort_order
 * @property string $created_date
 * @property string $created_user
 */
class ObjectRelationAPI extends BaseAPIObject
{
    public function fields()
    {
        $fields = parent::fields();
        return $fields;
    }

    public function getApiFields()
    {
        //$fields = parent::getApiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'object_id',
            'object_type',
            'object2_id',
            'object2_type',
            'relation_type'
        ];
        return $fields;
    }
}
