<?php

namespace backend\models;

use common\base\BaseCSVObject;
use common\base\BaseJSONObject;
use common\base\BasePHPObject;
use common\components\FActiveDataProvider;
use common\components\FConstant;
use common\components\FHtml;
use yii\helpers\BaseInflector;
use yii\helpers\StringHelper;


class ObjectCategoryCSV extends BaseJSONObject
{
    const COLUMNS_UPLOAD = ['image'];

    public static function tableName()
    {
        return 'dummy'; // TODO: Change the autogenerated stub
    }

    public function fields() {
        //return ['id', 'code', 'name', 'description', 'color', 'image', 'object_type', 'ip_address2', 'ip_address3'];
        return ['id', 'first_name', 'last_name', 'email', 'gender', 'ip_address', 'ip_address1', 'ip_address2', 'ip_address23'];
    }

    public static function getDbType()
    {
        return FConstant::DB_TYPE_PHP;
    }

    public function getFullUrl() {
        $url = FHtml::getFullURL($this->code);
        return $url;
    }
}