<?php

namespace backend\models;

use common\base\BasePHPObject;
use common\components\FActiveDataProvider;
use common\components\FConstant;
use common\components\FHtml;
use yii\helpers\BaseInflector;
use yii\helpers\StringHelper;


class ObjectCategoryPHP extends BasePHPObject
{
    const COLUMNS_UPLOAD = ['image'];

    public static function tableName()
    {
        return 'object_category'; // TODO: Change the autogenerated stub
    }

    public function fields() {
        return ['id', 'code', 'name', 'description', 'color', 'image', 'object_type', 'is_active', 'is_top', 'is_hot', 'order_by'];
    }

    public static function getDbType()
    {
        return FConstant::DB_TYPE_PHP;
    }

    public function getFullUrl() {
        $url = FHtml::getFullURL($this->code);
        return $url;
    }
}