<?php

namespace backend\models;

use common\base\BaseAPIObject;
use common\components\FApi;

/**
 * This is the model class for table "object_category".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $image
 * @property string $name
 * @property string $description
 * @property integer $sort_order
 * @property integer $is_active
 * @property integer $is_top
 * @property integer $is_hot
 * @property string $object_type
 * @property string $created_date
 * @property string $modified_date
 * @property string $application_id
 */
class ObjectCategoryAPI extends BaseAPIObject
{
    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        $folder = 'object-category';
        $image = FApi::getImageUrlForAPI($this->image, $folder);
        $this->image = $image;
        return $fields;
    }

    public function getApiFields()
    {
        //$fields = parent::getApiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'parent_id',
            'image',
            'name',
            'description',
            'is_top',
            'is_hot',
            'object_type'
        ];
        return $fields;
    }
}