<?php

namespace backend\modules\smartscreen\models;

use backend\modules\smartscreen\Smartscreen;
use Yii;
use common\components\FHtml;
use common\components\FModel;
use common\models\BaseModel;
use frontend\models\ViewModel;
use yii\helpers\ArrayHelper;

/**
 * Developed by Hung Ho (Steve): ceo@mozagroup.com | hung.hoxuan@gmail.com | skype: hung.hoxuan | whatsapp: +84912738748
 * Software Outsourcing, Mobile Apps development, Website development: Make meaningful products for start-ups and entrepreneurs
 * MOZA TECH Inc: www.mozagroup.com | www.mozasolution.com | www.moza-tech.com | www.apptemplate.co | www.projectemplate.com | www.code-faster.com
 * This is the customized model class for table "smartscreen_frame".
 */
class SmartscreenFrame extends SmartscreenFrameSearch
{
    const LOOKUP = [];

    const COLUMNS_UPLOAD = ['file',];

    public $order_by = 'sort_order asc,created_date desc,is_active desc,';

    const OBJECTS_RELATED = [];
    const OBJECTS_META = [];

    public static function getLookupArray($column = '') {
        if (key_exists($column, self::LOOKUP))
            return self::LOOKUP[$column];
        return [];
    }

    public function fields()
    {
        $fields = array_merge(parent::fields(), self::OBJECTS_RELATED);

        foreach (self::COLUMNS_UPLOAD as $field) {
            $this->{$field} = FHtml::getFileURL($this->{$field}, $this->getTableName());
        }
        return $fields;
    }

    public function afterFind()
    {
        if (empty($this->marginTop) || $this->marginTop > 100)
            $this->marginTop = 0;
        if (empty($this->marginLeft) || $this->marginLeft > 100)
            $this->marginLeft = 0;
        if (empty($this->percentWidth) || $this->percentWidth > 100)
            $this->percentWidth = 100 - $this->marginLeft;
        if (empty($this->percentHeight) || $this->percentHeight > 100)
            $this->percentHeight = 100 - $this->marginTop;
        return parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if (empty($this->marginTop) || $this->marginTop > 100)
            $this->marginTop = 0;
        if (empty($this->marginLeft) || $this->marginLeft > 100)
            $this->marginLeft = 0;
        if (empty($this->percentWidth) || $this->percentWidth > 100)
            $this->percentWidth = 100 - $this->marginLeft;
        if (empty($this->percentHeight) || $this->percentHeight > 100)
            $this->percentHeight = 100 - $this->marginTop;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        Smartscreen::clearCache();
        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        Smartscreen::clearCache();
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function prepareCustomFields() {
        parent::prepareCustomFields();
    }

    public static function getRelatedObjects() {
        return self::OBJECTS_RELATED;
    }

    public static function getMetaObjects() {
        return self::OBJECTS_META;
    }
}
